// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDmuWZ_alBHWJoIubLWM1Tj49gmuQlvDM',
    appId: '1:588873305693:web:93c7170d3e2677ee3407b4',
    messagingSenderId: '588873305693',
    projectId: 'quiz-d7b12',
    authDomain: 'quiz-d7b12.firebaseapp.com',
    storageBucket: 'quiz-d7b12.appspot.com',
    measurementId: 'G-BZ97C96RJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUVIeKkDv8R7SWfcGanmN94GZzc3clgXY',
    appId: '1:588873305693:android:2df6c925bdbae2d23407b4',
    messagingSenderId: '588873305693',
    projectId: 'quiz-d7b12',
    storageBucket: 'quiz-d7b12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx2oCw7aCeZixlJECTaV5Ss4sLy0V08z8',
    appId: '1:588873305693:ios:a012543f07a464623407b4',
    messagingSenderId: '588873305693',
    projectId: 'quiz-d7b12',
    storageBucket: 'quiz-d7b12.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx2oCw7aCeZixlJECTaV5Ss4sLy0V08z8',
    appId: '1:588873305693:ios:a012543f07a464623407b4',
    messagingSenderId: '588873305693',
    projectId: 'quiz-d7b12',
    storageBucket: 'quiz-d7b12.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDmuWZ_alBHWJoIubLWM1Tj49gmuQlvDM',
    appId: '1:588873305693:web:3cbe08b99721a0a23407b4',
    messagingSenderId: '588873305693',
    projectId: 'quiz-d7b12',
    authDomain: 'quiz-d7b12.firebaseapp.com',
    storageBucket: 'quiz-d7b12.appspot.com',
    measurementId: 'G-X050LDC5TC',
  );

}